### ISSUE TITLE
Profile "Varad" is not found on the system. 30787 3115 22792 19811 16754 3091

### ISSUE THREAD

**Issue by tusharc20** [Deadshot0x7/Wifipassword#1]
i tried running on windows 10  by administrator but it saying "Profile "Varad" is not found on the system.
30787 3115 22792 19811 16754 3091"
i m noob please help
![image](https://user-images.githubusercontent.com/73526935/115155250-a3e57b80-a09c-11eb-81cb-356b4b3a8695.png)

**Comment by Deadshot0x7** [comment]
Replace that with your network Name ssid

**Comment by tusharc20** [comment]
as soon as I start typing terminal is getting closed

**Comment by Deadshot0x7** [comment]
Right-click the bt file,  choose the edit option, and replace it with your Network SSID. Remember that should be connected with your system earlier and Last Digital are for effects purpose
